In [32]:
"""Import the relevant libraries"""
import numpy as np
import pandas as pd
import jax
import jax.random as random
import matplotlib.pyplot as plt
import jax.numpy as jnp

In [33]:
"""An array of 1000x10 is formed and is filled with random values as per standard normal distribution"""
X=np.random.randn(1000,10)


Box-Mueller transformation is done and samples are created

In [34]:
X

array([[-0.31684426,  1.03662443, -1.2598643 , ..., -2.30663845,
        -0.05339901,  0.27722158],
       [-1.58325817, -1.778672  ,  1.02593373, ..., -2.07729084,
        -0.76656059,  0.04055908],
       [-0.20223584,  0.24173262,  2.25299363, ..., -0.05600161,
         0.97850375,  0.94474802],
       ...,
       [-0.39486072,  0.5641165 ,  0.51273186, ..., -0.49244466,
        -0.80593473, -0.35283947],
       [-0.0140372 , -0.43011928, -0.90527799, ..., -0.55656619,
         1.40759279,  1.52941786],
       [-0.50126757,  0.47975776, -2.004846  , ...,  0.51238487,
         0.93753791,  0.07640953]])

These values are as per standard normal distribution

In [20]:
"""Covariance matrix  of order 10x10 is formed where the state of randomness is 42"""
covariance=random.uniform(jax.random.PRNGKey(42),(10,10))

In [21]:
covariance

DeviceArray([[0.684541  , 0.9428723 , 0.89513147, 0.4053936 , 0.15135467,
              0.33525085, 0.21541345, 0.94111454, 0.39515913, 0.0342294 ],
             [0.74429524, 0.33847547, 0.7611736 , 0.972476  , 0.6630137 ,
              0.94454443, 0.55559635, 0.07117987, 0.39472985, 0.04019296],
             [0.05007648, 0.11314845, 0.6809108 , 0.54507875, 0.6494565 ,
              0.38641107, 0.8278887 , 0.15131176, 0.02928579, 0.5129137 ],
             [0.259511  , 0.3685975 , 0.34400415, 0.08982337, 0.07031083,
              0.65979457, 0.6572846 , 0.1545142 , 0.21719241, 0.13127482],
             [0.7853644 , 0.5679945 , 0.6309763 , 0.13408446, 0.08149076,
              0.80145156, 0.98300517, 0.7719532 , 0.9083533 , 0.7691865 ],
             [0.24539304, 0.66746163, 0.6814374 , 0.8822509 , 0.47892106,
              0.10020494, 0.28252995, 0.71044123, 0.5421467 , 0.07213926],
             [0.25094116, 0.9231638 , 0.8877921 , 0.50331163, 0.9682282 ,
              0.7115189 , 0.8397

In [22]:
"""Similarly mean array is formed whose order is 1x10 and state of randomness is 42"""
mean = random.uniform(jax.random.PRNGKey(42),(1,10))

In [23]:
mean

DeviceArray([[0.6439377 , 0.32251573, 0.19349372, 0.8864933 , 0.84208524,
              0.19193006, 0.34513092, 0.2523831 , 0.6319014 , 0.65476775]],            dtype=float32)

In [24]:
"""In order to make covariance matrix symmetric I multiplied it by its transpose"""
covariance=covariance @ covariance.T

In [25]:
covariance

DeviceArray([[3.5479321, 2.6652634, 1.5491525, 1.4786901, 3.2968676,
              2.817199 , 3.041088 , 2.6464887, 2.4935434, 2.3560598],
             [2.6652634, 3.9965682, 2.4224358, 1.8041261, 3.1890795,
              2.621846 , 3.8584723, 2.0901668, 2.9667735, 2.48196  ],
             [1.5491525, 2.4224358, 2.319401 , 1.2797459, 2.3206882,
              1.7767437, 3.0913587, 1.5942326, 2.1030607, 1.477314 ],
             [1.4786901, 1.8041261, 1.2797459, 1.2901931, 2.2404516,
              1.1458551, 2.1751912, 1.1968237, 1.6848376, 1.3547455],
             [3.2968676, 3.1890795, 2.3206882, 2.2404516, 4.9834547,
              2.6135466, 4.405546 , 2.8699198, 3.117723 , 3.3193638],
             [2.817199 , 2.621846 , 1.7767437, 1.1458551, 2.6135466,
              2.8715296, 3.1003208, 2.5621917, 2.3174539, 2.0333154],
             [3.041088 , 3.8584723, 3.0913587, 2.1751912, 4.405546 ,
              3.1003208, 5.8278894, 3.0207882, 3.579455 , 3.3818047],
             [2.6464887, 2.

For the cholesky decomposition, symmetric matrix is required. Hence in order to make the matrix symmetric, I multiplied the covariance matrix with its transpose and that value is the new covariance which I'm going to use for the cholesky decomposition

In [35]:
"""Cholesky decomposition of covariance matrix is done and stored"""
Lowtriangle=np.linalg.cholesky(covariance)

In [36]:
Lowtriangle

array([[ 1.8835956e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4149871e+00,  1.4122251e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 8.2244432e-01,  8.9127976e-01,  9.2119855e-01,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 7.8503591e-01,  4.9093479e-01,  2.1334961e-01,  6.2239587e-01,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.7503055e+00,  5.0446618e-01,  4.6845374e-01,  8.3354414e-01,
         8.6669171e-01,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [ 1.4956497e+00,  3.5796064e-01,  2.4708246e-01, -4.1249290e-01,
   

In [37]:
"""Here multi-variate normal sample is created""" 
Y=mean+X@Lowtriangle.T

In univariate normal distribution, Y=T+PX where T is mean vector and P is standard deviation. For multivariate normal distribution, Y=T+LX. Here we have the covariance matrix instead of variance. Like in univariate distribution where we take the square root of variance into consideration, here we take the square root of symmetric positive definite matrix i.e. Cholesky factor into consideration.

In [29]:
Y

DeviceArray([[ 2.3758683 ,  3.185282  ,  2.5491614 , ...,  3.7827063 ,
               5.641053  ,  1.9062945 ],
             [-0.7430111 , -0.83479345, -0.5266848 , ..., -1.1068221 ,
               0.09738332, -0.2202577 ],
             [ 2.116631  ,  0.29399127, -1.2149109 , ...,  2.7434134 ,
               1.2140694 ,  1.8353761 ],
             ...,
             [ 2.615984  ,  0.5686573 ,  0.79592866, ...,  0.9872347 ,
               0.6438987 ,  2.314989  ],
             [-1.4085294 , -2.5080042 , -2.833181  , ..., -0.77959096,
              -0.3331383 , -3.0973082 ],
             [-0.4956833 , -1.9133315 , -0.79805374, ..., -1.1475973 ,
              -2.3006606 , -2.114443  ]], dtype=float32)

In [30]:
"""Mean of the normal sample"""
jnp.mean(Y,axis=0)

DeviceArray([0.70344687, 0.3471242 , 0.23346965, 0.9225257 , 0.9408433 ,
             0.22679904, 0.3866526 , 0.31112766, 0.6957183 , 0.6818863 ],            dtype=float32)

In [31]:
"""Covariance of the normal sample"""
jnp.cov(Y.T)

DeviceArray([[3.8109794, 2.8519979, 1.6293215, 1.5724703, 3.5271146,
              3.015753 , 3.295258 , 2.8393233, 2.6584394, 2.5668786],
             [2.8519979, 4.1096363, 2.4338102, 1.8329178, 3.393015 ,
              2.7055209, 3.995627 , 2.2215157, 3.0890918, 2.6914928],
             [1.6293215, 2.4338102, 2.2704747, 1.2405025, 2.3219671,
              1.8068421, 3.1154137, 1.6478155, 2.1558828, 1.5283746],
             [1.5724703, 1.8329178, 1.2405025, 1.2923086, 2.336769 ,
              1.1883239, 2.202296 , 1.2635748, 1.697153 , 1.4667444],
             [3.5271146, 3.393015 , 2.3219671, 2.336769 , 5.211194 ,
              2.764313 , 4.5571966, 3.0205228, 3.2324889, 3.5241122],
             [3.015753 , 2.7055209, 1.8068421, 1.1883239, 2.764313 ,
              2.9839537, 3.23864  , 2.6885304, 2.4257512, 2.1553555],
             [3.295258 , 3.995627 , 3.1154137, 2.202296 , 4.5571966,
              3.23864  , 6.019063 , 3.1767914, 3.7302458, 3.5615282],
             [2.8393233, 2.

If I compare both mean values and covariance values i.e. mean and covariance that I had randomly selected and that I found out from Y , they are very near to each other